models/User.php
<?php

namespace app\models;

use app\helpers\SortHelper;
use \Yii;
use yii\base\Exception;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use app\helpers\FileHelper;
use app\helpers\ImageHelper;
use yii\db\Transaction;
use app\helpers\WidgetHelper;
use app\helpers\ArrayHelper;

/**
 * Class User
 *
 * @property string $email;
 * @property string $username;
 * @property string $password;
 * @property int $status;
 * @property boolean $is_activated_email
 * @property string $email_activation_key;
 * @property string $current_oauth_provider
 *
 * @package app\models
 */
class User extends BaseModel implements \yii\web\IdentityInterface
{
    const EMAIL_NOT_ACTIVATED = 0;
    const EMAIL_ACTIVATED = 1;
    const TYPE_USER = 0;
    const TYPE_ADMINISTRATOR = 1;
    const SCENARIO_SETTINGS = 'settings';

    const ANONYMOUS_ID = 1;


    private $_avatar;
    protected $_oauthErrors = [];
    private $_oauth;
    private $_favoritePostIds;
    private $_transaction;
    private $_forumUser;



    public static function ratingMinEdges() {
        return [
            'red' => 400,
            'blue' => 200,
            'yellow' => 100,
            'green' => 20,
            'gray' => 0,
        ];
    }


    public function getCurrentBadgeColor()
    {
        foreach(self::ratingMinEdges() as $color => $edge){
            if($this->rating >= $edge){
                return $color;
            }
        }

        return 'gray';
    }

    public function getNextBadgeNeededRating()
    {
        $edges = self::ratingMinEdges();
        sort($edges, SORT_ASC);
        $nextEdge = 0;
        foreach($edges as $edge){
            if($this->rating < $edge)
            {
                $nextEdge = $edge;
                break;
            }
        }

        return $nextEdge - $this->rating;
    }

    private $_linkedAccounts = false;
    private $_settings = [
        'show_adult' => null,
        'expand_posts' => null
    ];
    public $file_name;

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_SETTINGS] = ['username', 'password'];
        return $scenarios;
    }

    public function rules()
    {
        return [

            [['username'], 'filter', 'filter' => 'trim'],
            [['username'], 'filter', 'filter' => function($value){
                return str_replace(' ', '_', $value);
            }],
            [['username'], 'string', 'min' => 2, 'max' => 50],

//            [['password'], 'string', 'min' => 6, 'max' => 16],

            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'email'],
            ['email', 'unique', 'targetClass' => '\app\models\User', 'message' => "Email address '{value}' has already been taken."],

            ['status', 'number', 'integerOnly' => true],

            ['current_oauth_provider', 'in', 'range' => UserOauth::possibleSocialAccounts()],

            ['is_activated_email', 'default', 'value' => self::EMAIL_NOT_ACTIVATED],
            ['is_activated_email', 'boolean'],

            ['is_admin', 'default', 'value' => self::TYPE_USER],
            ['is_admin', 'boolean'],

            ['lastvisit_at', 'safe'],
            [['profile', 'settings'], 'safe'],
            [['gender','money_make'], 'number', 'integerOnly' => true],

            [['payout_type', 'wallet', 'full_name', 'icq',
                'payment_address', 'payment_city', 'payment_postcode','payment_country','payment_phone'], 'string']
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord && empty($this->username)) {
            $this->username = $this->getEmailName();
        }
        if ($this->scenario === self::SCENARIO_SETTINGS) {
            $this->saveSettings();
        }

        if($insert && !isset($this->status)){
            $this->status = self::STATUS_ACTIVE;
        }
        return parent::beforeSave($insert);
    }

    public function saveSettings()
    {
        foreach ($this->_settings as $name => $value) {

        }
    }

    public function beforeDelete()
    {
        $this->_transaction = $this->getDb()->beginTransaction();

        foreach ($this->posts as $post) {
            $post->delete();
        }

        UserFavoritePost::deleteAll(['user_id' => $this->id]);
        UserSeenPost::deleteAll(['user_id' => $this->id]);

        return parent::beforeDelete();
    }

    public function removeRemoteComments()
    {
        $config = WidgetHelper::getConfig('', 2);
        $url = $config['mainUrl'] . "/v1/user/delete";
        unset($config['mainUrl']);
        $config['id'] = $this->id;
        $ch = curl_init();
        $dataString = http_build_query($config);

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, count($config));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $dataString);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $result = curl_exec($ch);

        $errorNumber = curl_errno($ch);
        $errorMessage = curl_error($ch);
        curl_close($ch);

        if (!$errorNumber) {
            $result = Json::decode($result);
            if (isset($result['status'])
                && ($result['status'] == 'ok' || (isset($result['code']) && $result['code'] == '404'))
            ) {
                return true;
            } else {
                throw new Exception("Coudn't remove remote comments user, request failed, response - " . json_encode($result));
            }
        }
        throw new Exception('Curl error requesting "' . $url . '": #' . $errorNumber . ' - ' . $errorMessage);
    }

    public function afterDelete()
    {
        if ($this->_transaction instanceof Transaction
            && $this->removeRemoteComments()
        ) {
            $this->_transaction->commit();
        }
        parent::afterDelete();
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (
            isset($changedAttributes['status']) &&
            (int)$this->status === self::STATUS_BANNED
        ) {
            $this->setPostsBanned();
        } else if (
            isset($changedAttributes['status']) &&
            (int)$changedAttributes['status'] === self::STATUS_BANNED &&
            (int)$this->status === self::STATUS_ACTIVE
        ) {
            $this->unsetPostsBanned();
        }

        parent::afterSave($insert, $changedAttributes);
    }


    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return self::findOne(['activkey' => $token, 'status' => self::STATUS_ACTIVE]);
    }

    public static function findIdentityByEmailKey($key)
    {
        return self::findOne(['email_activation_key' => $key, 'status' => self::STATUS_ACTIVE]);
    }

    public static function findByPasswordResetToken($token)
    {
        return self::findOne(['password_reset_token' => $token, 'status' => self::STATUS_ACTIVE]);
    }

    public static function findByEmail($email)
    {
        return self::findOne(['email' => $email]);
    }


    /**
     * Finds user by username
     *
     * @param  string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->activkey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->activkey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->activkey = Yii::$app->security->generateRandomString();
    }

    public function generateEmailKey()
    {
        $this->email_activation_key = Yii::$app->security->generateRandomString();
    }

    public function getEmailKey()
    {
        return $this->email_activation_key;
    }

    public function activateEmail()
    {
        $this->is_activated_email = self::EMAIL_ACTIVATED;
        return $this->save();
    }

    public static function getByOauth($attributes, $provider)
    {
        $attributes = self::normalizeAttributes($attributes, $provider);

        $userOauth = UserOauth::findOne(['identifier' => $attributes['id'], 'provider' => $provider]);
        if ($userOauth !== null) {
            $user = $userOauth->user;
            if ($user !== null) {
//                $user->setCurrentOauth($userOauth);
                return $user;
            }
        }

        if (isset($attributes['email'])) {
            $user = self::findByEmail($attributes['email']);
            if (!empty($user)) {
                if (!$user->addSocialAccount($attributes, $provider)) {
                    \Yii::$app->session->setFlash('error', 'Some errors occurred while adding new social account to existing user');
                }
                return $user;
            }
        }

        return self::createBySocial($attributes, $provider);
    }

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: mactra
 * Date: 13.11.15
 * Time: 15:50
 */

namespace app\controllers;

use Yii;
use app\components\Controller;
use app\models\ResetPasswordForm;
use app\models\UserOauth;
use app\models\UserSettingsForm;
use yii\base\InvalidParamException;
use app\models\User;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use app\components\SphinxDataProvider;
use app\models\Post;
use app\models\FilterUserPost;

class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['profile', 'reset-password']
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionSocialAccounts()
    {
        return $this->render('social-accounts');
    }


//    public function actionRequestPasswordReset()
//    {
//        $model = new PasswordResetRequestForm();
//
//        if ($model->load(Yii::$app->request->post())) {
//
//            $validations = $this->performAjaxValidation($model);
//
//            if($validations !== false)
//                return $validations;
//
//            if (!$model->validate()){
//                return 'error';
//            }
//
//            $user = User::findOne([
//                'email' => $model->email,
//            ]);
//
//            if($user)
//            {
//                $user->generatePasswordResetToken();
//                if($user->save() && $model->sendEmail($user->password_reset_token))
//                    return 'ok';
//            }
//        }
//
//        return 'error';
//    }

    // todo: move to site controller
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('reset-password', [
            'model' => $model,
        ]);
    }


    public function actionSettings()
    {
        $formModel = new UserSettingsForm();
        if ($formModel->load($_POST)) {
            $validations = $this->performAjaxValidation($formModel);
            if ($validations !== false) {
                return $validations;
            }

            if ($formModel->applySettings()) {
                Yii::$app->session->setFlash('success', 'Settings have been changed');
                return $this->refresh();
            }
        }

        return $this->render('settings', ['model' => $formModel]);
    }

    public function actionSettingAvatar()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $formModel = new UserSettingsForm();
        if ($formModel->load(Yii::$app->request->post()) && $formModel->applyAvatar()) {
            return [
                'status' => 'success',
                'avatar' => $formModel->profileAvatar
            ];
        }

        return [
            'status' => 'error',
            'errors' => $formModel->getErrors()
        ];
    }

    public function actionUnlink($provider)
    {
        if (!in_array($provider, UserOauth::possibleSocialAccounts())) {
            throw new NotFoundHttpException;
        }

        if (\Yii::$app->user->identity->unlinkSocialAccount($provider)) {
            \Yii::$app->session->setFlash('success', 'You successfully unlinked your ' . ucfirst($provider) . " account");
        } else {
            \Yii::$app->session->setFlash('error', "We couldn't unlink your " . ucfirst($provider) . " account");
        }

        return $this->redirect(['user/settings']);
    }

    public function actionSetDefault($provider)
    {
        if (!in_array($provider, UserOauth::possibleSocialAccounts())) {
            throw new NotFoundHttpException;
        }

        \Yii::$app->user->identity->current_oauth_provider = $provider;

        if (\Yii::$app->user->identity->save()) {
            \Yii::$app->session->setFlash('success', 'You set as default your ' . ucfirst($provider) . " account");
        } else {
            \Yii::$app->session->setFlash('error', "We couldn't set as default your " . ucfirst($provider) . " account");
        }

        return $this->redirect(['user/settings']);
    }

    public function actionSetDefaultAvatar()
    {
        $user = Yii::$app->user->identity;
        $user->current_oauth_provider = null;

        if ($user->update(true, ['current_oauth_provider'])) {
            Yii::$app->session->setFlash('success', 'Your profile avatar set as default');
        } else {
            Yii::$app->session->setFlash('error', 'Error set default avatar');
        }
        return $this->redirect(['user/settings']);
    }

    public function actionProfile($id = null, $username = null)
    {
        if(!empty($id)){
            $user = User::findOne($id);
        }else{
            $user = User::findOne(['username' => $username]);
        }


        if (empty($user)) {
            throw new NotFoundHttpException('User not found');
        }

        $dataQuery = Post::find()
            ->from('post p')
            ->with([
                'postBlocks',
                'tags',
                'author'
            ]);

        $filter = new FilterUserPost([
            'sphinxClient' => Yii::$app->sphinxClient->getClient(),
            'user' => $user
        ]);

        $filter->applyClientFilters();

        $defaultSort = $filter->type === 'best' ? ['rating' => SORT_DESC, 'live_at' => SORT_DESC]
            : ['live_at' => SORT_DESC];

        $dataProvider = new SphinxDataProvider([
            'cacheDuration' => 60,
            'query' => $dataQuery,
            'sphinxClient' => $filter->getSphinxClient(),
            'indexName' => $filter->indexName,
            'primaryModelKey' => 'p.id',
            'sphinxQuery' => $filter->getSphinxQuery(),
            'useSqlSortMode' => true,
            'sortingAttributes' => [
                'live_at' => 'ts_live_at',
                'rating' => 'rating'
            ],
            'sort' => [
                'defaultOrder' => $defaultSort,
            ],
            'pagination' => [
                'pageSize' => Yii::$app->params['itemsPerPage'],
                'defaultPageSize' => Yii::$app->params['itemsPerPage']
            ]
        ]);

        return $this->render('public-profile', [
            'filter' => $filter,
            'user' => $user,
            'dataProvider' => $dataProvider
        ]);
    }


}

views/user/public-profile.php
<?php
/**
 * @var \app\models\User $user
 * @var $dataProvider \app\components\SphinxDataProvider
 */

use app\assets\UserAsset;
use app\components\ListView;
use app\models\Post;
use yii\helpers\Json;
use yii\helpers\Url;
use app\widgets\ScrollPager;
use app\helpers\WidgetHelper;
use yii\bootstrap\Html;
use yii\web\View;

UserAsset::register($this);

$seenPostIds = [];
if (!Yii::$app->user->isGuest) {
    //switched off make seen posts for until we complete with it
    $this->registerJs("$(document).on('scroll_1', scrollPostsHandler); initProccessSeenPosts($('.item'));");
//    echo Html::hiddenInput('make-seen-url', Url::to(['post/make-seen']));
//    $seenPostIds = Yii::$app->user->identity->getSeenPostIds(['post_id' => $dataProvider->getSphinxIds()]);
    $this->registerJs('var userOptions = ' . Json::encode(Post::getUserSettings()) . ';', $this::POS_HEAD);
}

$this->registerMetaTag([
    'name' => 'description',
    'content' =>  \Yii::$app->name . ' - Awesome daily updated Owned Videos, Pictures & Gifs - Visit us to see more!'
], 'description');

$this->registerMetaTag([
    'name' => 'keywords',
    'content' => 'owned,jokes,fun,humour,funny videos,epic,fail,win,funny pics,like a boss,forever alone,meme,gifs,funny gifs,trolling'
], 'keywords');

$config = WidgetHelper::getConfig(2);
$jsonConfig = Json::encode($config);
$ck = WidgetHelper::getScriptInView('//js/widget', ['config' => $config]);
$this->registerJs($ck, View::POS_END);

$pageParam =  $dataProvider->pagination->pageParam;
$pageNumber = !empty($_GET[$pageParam]) ? $_GET[$pageParam] : 1;
$link = '';

if (!\Yii::$app->user->isGuest) {
    echo Html::hiddenInput('add-to-favorite-url', Url::to(['post/toggle-favorite']));
    $this->registerJs("$('body').on('click', '.add-to-favorite', addToFavoriteHandler)");
}

if($postId = \Yii::$app->request->get('p')){
    $this->registerJs("scrollToElement($('[data-key=\"$postId\"]'))", View::POS_READY);
    if($pageNumber>1){
        $postsNumber = ($pageNumber-1) * $dataProvider->pagination->pageSize;
        $link = Html::a("Show previous $postsNumber posts", parse_url(\Yii::$app->request->getUrl(),PHP_URL_PATH));
    }
}

$collapsePosts = \Yii::$app->user->isGuest || !(bool) \Yii::$app->user->identity->getSettings('expand_posts');
$jsAjaxListEvent = $collapsePosts ?
    "if(typeof $.fn.expandPostAjaxListEvent === \"function\"){
        $(this).expandPostAjaxListEvent();
     }" : "";


?>

<div class="row">
    <div class="col-md-12">
        <!-- Page Header -->
        <div class="page-header position-relative">
            <div class="header-title">
                <h1>
                    <?= $user->username ?> profile
                </h1>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="profile-container">
            <div class="profile-header well row">
                <div class="col-lg-2 col-md-4 col-sm-12 text-center">
                    <?= $user->publicProfileAvatar ?>
                </div>
                <div class="col-lg-4 col-md-8 col-sm-12 profile-info text-center">
                    <div class="header-fullname"><?= $user->username ?></div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-12 stats-col">
                    <div class="stats-value pink"><?= $user->rating ?></div>
                    <div class="stats-title">Rating</div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-12 stats-col">
                    <div class="stats-value pink">
                        <a href="<?= $user->getAuthorUrl() ?>">
                            <?= $user->getPosts()->count(); ?>
                        </a>
                    </div>
                    <div class="stats-title">Number of posts</div>
                </div>

                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-12 stats-col">
                    <div class="stats-value pink">
                        <a href="<?= Url::to(['album/user', 'id' => $user->id]) ?>">
                            <?= $user->getImages()->count(); ?>
                        </a>
                    </div>
                    <div class="stats-title">Number of images</div>
                </div>
            </div>
            <div class="profile-body">
                <div class="col-lg-12">
                    <div class="tabbable">
                        <ul class="nav nav-tabs tabs-flat  nav-justified" id="myTab11">
                            <li class="<?= $filter->type === 'overview' ? 'active' : '' ?>">
                                <a href="<?= Url::to(['user/profile', 'id' => $user->id, 'type' => 'overview']) ?>" class="rlinks">
                                    Overview
                                </a>
                            </li>
                            <li class="<?= $filter->type === 'commented' ? 'active' : '' ?>">
                                <a href="<?= Url::to(['user/profile', 'id' => $user->id, 'type' => 'commented']) ?>" class="rlinks">
                                    Commented
                                </a>
                            </li>
                            <li class="<?= $filter->type === 'favorites' ? 'active' : '' ?>">
                                <a href="<?= Url::to(['user/profile', 'id' => $user->id, 'type' => 'favorites']) ?>" class="rlinks">
                                    Liked
                                </a>
                            </li>
                            <li class="<?= $filter->type === 'my' ? 'active' : '' ?>">
                                <a href="<?= Url::to(['user/profile', 'id' => $user->id, 'type' => 'my']) ?>" class="rlinks">
                                    Own
                                </a>
                            </li>
                        </ul>
                        <div class="col-md-12">
                            <?php
                            echo ListView::widget([
                                'id'=>'main-list-view',
                                'summary' => false,
                                'dataProvider' => $dataProvider,
                                'itemView' => '/post/_post',

                                'itemOptions' => [
                                    'class' => ''
                                ],

                                'viewParams' => [
                                    'seenIds' => isset($seenPostIds) ? $seenPostIds : [],
                                    'page' => $pageNumber
                                ],

                                'pager' => [
                                    'class' => ScrollPager::className(),
                                    'item' => '.item',
                                    'enabledExtensions' => [
                                        ScrollPager::EXTENSION_PAGING,
                                        ScrollPager::EXTENSION_SPINNER
                                    ],
                                    'eventOnRender' => $collapsePosts ? 'function(items){
                                         $(items).each(function() {
                                            if(typeof $.fn.expandPostAjaxList === "function"){
                                                $(this).expandPostAjaxList();
                                            }
                                        });
                                    }' : null,

                                    'eventOnRendered' => "function(items) {
                                        var \$items = $(items);
                                        initProccessSeenPosts(\$items);
                                        \$items.each(function() {
                                             if (typeof $.fn.initGifPlayer === 'function') {
                                                 $('[id^=\"gifPlayer-\"]', this).initGifPlayer();
                                             }
                                             $jsAjaxListEvent
                                        });
                                    }"
                                ]
                            ]);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/user/reset-password.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var \app\models\ResetPasswordForm $model
 */
$this->title = 'Reset password';
?>
<div class="site-reset-password col-sm-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Please choose your new password:</h3>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

views/user/social-accounts.php
<?php
use yii\helpers\Html;
use app\models\UserOauth;
use yii\helpers\Url;
use app\helpers\WidgetHelper;
use yii\web\View;

/* @var $user \app\models\User */
$user = \Yii::$app->user->identity;
$config = WidgetHelper::getConfig(2);
$config['avatarUploader']=[
    'clicker' => '[data-uploader="avatar-image"]',
    'progressContainer' => '[data-uploader="progress-container"]',
    'isMultiple' => false,
];
$ck = WidgetHelper::getScriptInView('//js/widget', ['config' => $config]);
$this->registerJs($ck, View::POS_END);

?>

<h3 class="col-sm-12">Social accounts</h3>
<div class="row">
    <div class="col-xs-12">
        <table id="social-accounts-table" class="table">
            <?php foreach (UserOauth::possibleSocialAccounts() as $provider) { ?>
                <tr>
                    <?php if ($user->isLinkedAccount($provider)) { ?>
                        <?php
                        /* @var $oauth app\models\UserOauth */
                        $oauth = $user->getLinkedAccount($provider)
                        ?>
                        <td>
                            <h4><?= ucfirst($oauth->provider) ?></h4>
                        </td>
                        <td>
                            <?= Html::a("Unlink", ['user/unlink', 'provider' => $oauth->provider], ['class' => 'btn btn-danger']); ?>
                        </td>
                        <td>
                            <h4><?= ucfirst($oauth->display_name) ?></h4>
                        </td>
                        <td>
                            <div class="social-image-wrapper text-center">
                                <?= Html::img($oauth->getAvatarUrl(), ['class' => 'img-thumbnail']); ?>
                            </div>
                        </td>
                        <td class="text-center">
                            <?php if ($user->current_oauth_provider !== $provider) { ?>
                                <?=
                                Html::a('Set avatar', [
                                    'user/set-default',
                                    'provider' => $oauth->provider
                                ], ['class' => 'btn btn-warning'])
                                ?>
                            <?php } ?>

                        </td>
                    <?php } else { ?>
                        <td>
                            <h4><?= ucfirst($provider) ?></h4>
                        </td>
                        <td>
                            <a class="btn btn-primary"
                               href="<?= Url::toRoute(['site/auth', 'authclient' => $provider]) ?>">
                                Link
                            </a>
                        </td>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>

                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <tr class="custom-avatar-row">
                <td><h4>Upload custom avatar</h4></td>
                <td></td>
                <td></td>
                <td>
                    <div class="user-avatar social-image-wrapper text-center">
                        <label>
                            <input id="user-avatar-input" type="file" name="loadedImages" hidden="hidden">
                            <div class="img-thumbnail img-avatar"
                                 style="background-image: url(<?= $model->profileAvatar ?>)">
                                <img src="<?= $model->profileAvatar ?>" alt="<?= $model->profileAvatar ?>">
                            </div>
                            <div class="absolute-progress">
                                <div class="progress" hidden="hidden">
                                    <div class="bar" style="width: 0%;"></div>
                                </div>
                            </div>
                        </label>

                        <input type="hidden" name="<?= $model->formName() ?>[0][file_name]">
                        <input type="hidden" name="<?= $model->formName() ?>[0][upload_name]">
                    </div>
                </td>
                <td class="text-center">
                    <?php if ($model->profileAvatar !== $model->avatar) { ?>
                        <?= Html::a('Set avatar', ['user/set-default-avatar'], ['class' => 'btn btn-warning']) ?>
                    <?php } ?>
                </td>
            </tr>
        </table>
    </div>
</div>