controllers/SiteController.php
<?php

namespace app\controllers;

use app\controllers\actions\AjaxCaptchaAction;
use app\components\Controller;
use app\models\Image;
use app\models\MainSearchForm;
use app\models\User;
use app\models\PasswordResetRequestForm;
use Yii;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\HttpException;
use app\components\SphinxDataProvider;
use app\models\Post;
use yii\web\Response;
use app\models\UserSettings;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => AjaxCaptchaAction::className(),
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout = '1-column';
        return $this->render('index');
    }


    public function actionSearch()
    {
        $searchForm = new MainSearchForm();
        $searchForm->prepareQuery();

        $dataProviderConfig = [
            'sphinxClient' => $searchForm->sphinxClient,
            'primaryModelKey' => 'id',
            'sphinxQuery' => $searchForm->sphinxQuery,

        ];

        $view = 'search_images';

        if($searchForm->getIsImagesRequest())
        {
            $dataProviderConfig['query'] =  Image::find()
                ->andWhere('status=:normal OR status=:processing', [':normal'=>Image::STATUS_NORMAL, ':processing'=>Image::STATUS_PROCESSING]);

            $pageSize = \Yii::$app->params['imagesPerPage'];

            $dataProviderConfig['indexName'] = !empty(Yii::$app->params['indexes']['main'])
                ? Yii::$app->params['indexes']['main'] : 'pah_main_search pah_main_search_delta';

        }else{
            $view = 'search_posts';

            $pageSize = \Yii::$app->params['itemsPerPage'];

            $dataProviderConfig['query'] = Post::find()->from('post p')
                ->with(['postBlocks', 'tags', 'author']);

            $dataProviderConfig['sortingAttributes'] = [
                'live_at' => 'ts_live_at',
            ];

            $dataProviderConfig['sort'] = [
                'defaultOrder' => ['live_at' => SORT_DESC]
            ];

            $dataProviderConfig['indexName'] =  !empty(Yii::$app->params['indexes']['posts'])
                ? Yii::$app->params['indexes']['posts'] : 'pah_posts_search pah_posts_search_delta';

        }

        $dataProviderConfig['pagination'] = [
            'userSettingName' => UserSettings::NAME_ALBUMS_PAGE_SIZE,
            'pageSize' => $pageSize,
            'defaultPageSize' => $pageSize,

        ];

        $dataProvider = new SphinxDataProvider($dataProviderConfig);

        return $this->render($view, ['searchForm' => $searchForm, 'dataProvider' => $dataProvider]);
    }

    public function onAuthSuccess($client)
    {
        $attributes = $client->getUserAttributes();
        $provider = $client->getId();

        if (\Yii::$app->user->isGuest)
        {
            $user = User::getByOauth($attributes, $provider);
            if (!$user->hasErrors() && empty($user->getOauthErrors()))
            {
                if($user->getIsActive()){
                    if(Yii::$app->user->login($user, 5 * 24 * 60 * 60)){
                        Yii::$app->session->setFlash('success', 'Welcome to '. \Yii::$app->name .'!');
                    }else{
                        Yii::$app->session->setFlash('error', "We couldn't login you for some reason");
                    }
                }else{
                    Yii::$app->session->setFlash('danger', 'Your account is not active!');
                }
            } else
            {
                if(!empty($user->getOauthErrors())){
                    $errors['oauth_errors'] = $user->getOauthErrors();
                }
                if($user->hasErrors()){
                    $errors['user'] = $user->getErrors();
                }

                $errors = json_encode($errors);
                Yii::$app->session->setFlash('error', "We could not login you because of $errors");
            }
        } else {
            $attributes = User::normalizeAttributes($attributes, $provider);
            if (Yii::$app->user->identity->addSocialAccount($attributes, $provider)) {
                Yii::$app->session->setFlash('success', "You successfully linked your " . ucfirst($provider) . " account");
            } else {
                $message = Yii::$app->user->identity->getOauthErrors('endUserMessage')
                    ? Yii::$app->user->identity->getOauthErrors('endUserMessage')
                    : "We couldn't link you account for some reason";

                Yii::$app->session->setFlash('warning', $message);
            }
        }
    }

    public function actionReset()
    {
        $this->layout = 'clean';

        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $user = User::findOne(
                [
                    'email' => $model->email,
                ]
            );
            $user->generatePasswordResetToken();
            if ($user->save() && $model->sendEmail($user->password_reset_token)) {
                \Yii::$app->session->setFlash('success', 'Check your email for further instructions');
                return $this->goHome();
            }
        }

        return $this->render('reset', compact('model'));
    }


    public function actionLogin()
    {
        $this->layout = 'clean';

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $resetPasswordModel = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            if (!\Yii::$app->user->identity->getIsEmailActivated()) {
                \Yii::$app->session->setFlash('warning', 'Your email is not activated');
            }

            return $this->redirect(\Yii::$app->user->getFiltredReturnUrl());
        }

        return $this->render('login', compact('model', 'resetPasswordModel'));
    }

    public function actionSignup()
    {
        $this->layout = 'clean';

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {

            $validations = $this->performAjaxValidation($model);
            if ($validations !== false)
                return $validations;

            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {

                    $this->sendActivationEmail($user);

                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', compact('model'));
    }

    protected function sendActivationEmail(User $user)
    {

        $link = Url::toRoute(['site/activate', 'code' => $user->getEmailKey()], true);

        $to = $user->email;
        $subject = "Activate your account";
        $message = "Use this link to activate your email: " . Html::a('Activate', $link);
        // todo - get addres and subject from config
        $headers = 'From: Welcome to ' . \Yii::$app->name . ' <system@' . \Yii::$app->name . '>' . "\r\n" .
            'X-Mailer: PHP/' . phpversion() . "\r\n";

        $headers .= 'Content-type: text/html; charset=utf-8';

        $res = mail($to, $subject, $message, $headers);

        if ($res) {
            \Yii::$app->session->setFlash('success', 'We sent you activation email');
        } else {
            \Yii::$app->session->setFlash('error', 'We were unable to send you activation email, please try to activate you accont later');
        }

        return $res;
    }

    public function actionActivate($code)
    {
        $user = User::findIdentityByEmailKey($code);

        if (empty($user)) {
            \Yii::$app->session->setFlash('error', 'Wrong activation link');

            return $this->goHome();
        }

        if ($user->is_activated_email) {
            \Yii::$app->session->setFlash('success', 'You have already activated your email');
        } else {
            if ($user->activateEmail()) {
                \Yii::$app->session->setFlash('success', 'You successfully activated your email. Thank you.');
            } else {
                \Yii::$app->session->setFlash('error', "We couldn't activate your email for some reason. Please try again later.");
            }
        }

        return $this->goHome();
    }

    public function actionLogout()
    {
        $url = \Yii::$app->user->getFiltredReturnUrl();
        Yii::$app->user->logout();
        return $this->redirect($url);
    }

    public function actionContact($adv = null)
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted', 'Thank you for contacting us. We will respond to you as soon as possible.');
            return $this->refresh();
        }

        if ($adv !== null) {
            $model->subject = 'Advertising';
        }
        return $this->render('contact', compact('model'));
    }

    public function actionPrivacy()

views/site/abuse.php
<style>
    h2 {
    font-family:georgia;
    font-size:25px;
    font-weight:bold;
    color:#5b5b32;
    padding:0px;
    margin:0px;
    }
    
    li {
    font-size:12px;
    font-family:verdana;
    line-height:30px;
    color:#474726;
    }
    
    #bbinstructions{
    font-size:12px;
    font-family:verdana;
    line-height:28px;
    color:#474726;
    }
    
    #tos p{
    color:#474726;
    font-family:verdana;
    font-size:11px;
    line-height:18px;
    text-align:left;
    }
</style>






<div style="width:700px;text-align:left;">


<h2><center>Terms and Agreements</center></h2>

<br><br>



<p>PimpAndHost.com is an Online Service Provider under Title II of the Digital Millennium Copyright Act, 17 U.S.C. Section 512 ("DMCA").<br><br></p> 
 
<p>We treat every abuse very seriously. If you wish to report a copyright infringement you have to it properly in accordance with DMCA procedure.<br><br></p> 
 
<p>To file a valid DMCA Notice, you need to provide us with the following information:</p> 
 
<p><b>1.</b> Identify and establish yourself as an owner of copyrighted work or provide proof of exclusive
rights that you believe were infringed. If you are a person acting on behalf of such owner, please
include proof (copy of an agreement, power of attorney or authorization letter) for verification
purposes.<br><br></p> 
 
<p><b>2.</b> Include all your contact information: your name, business mailing address, day time phone
number, and email address.<br><br></p> 
 
<p><b>3.</b> Identify the copyrighted work that you believe is being infringed.<br><br></p> 
 
<p><b>4.</b> Inform us of the location on the web (Internet) of copyrighted materials that allegedly are infringing your copyrights, of the location of these materials on PimpAndHost.com by including URLs on PimpAndHost.com containing aforementioned materials. Do not send any file attachments, images, PDFs e.t.c., we will not open them for security reasons. Include only the list of URLs in a simple text format, one URL per line.<br><br></p> 
 
<p><b>5.</b> It is very important for you to make sure that you only include material you have the authority over.<br><br></p> 
 
<p><b>6.</b> In your report include a statement worded: "I believe in good faith that use of the
aforementioned material is not authorized by the copyright owner, its agents, or the law".<br><br></p> 
 
<p><b>7.</b> Write a statement that the information in the notice is accurate, under penalty of perjury.
If filing your notice on paper, it must be signed with your actual signature. If filing electronically
please include electronic signature with your report.<br><br></p> 
 
<p><b class="f_12px">To file your DMCA report, your valid DMCA Notice must be sent to PimpAndHost.com email:</b> <b class="f_courier">abuse@pimpandhost.com</b><br><br></p> 
 
<h1 style="color:red">** IMPORTANT: Make sure you ALWAYS include LINKS to the infringing content, else we can`t identify it and remove it for you **</h1>

<p><u>Please note that only those abuse reports sent to abuse@pimpandhost.com will be accepted for a review.</u><br><br></p> 
 
<p>Action and Notification:<br></p> 
 
<p>PimpAndHost.com will follow the necessary procedures to investigate and if needed to properly enforce
rights of copyright holders. When we to the best of our ability determine that your abuse report
is in fact valid and truthful we will schedule the infringing material for removal, which takes
anywhere from 8 to 24 hours. We do not notify you. Please wait at least 30 hours and check if
material has been removed before re-filing a report.<br><br></p> 
 
<h2>Terms of service</h2>
<div style="text-align:left;">
<ol>
 1.Only one account is allowed per person. If we found user signing up for more than one accounts, we will ban   All accounts of user.<br>
<br>
2.Uploading offensive material including but not limited to: Beastiality, Scat, Any sexualy explicit pictures depicting minors, copyright material, or any illegal stuff will   result in permanent ban of your account. If you are not a account holder and we find you are   uploading offensive images, they will be deleted on the spot and your ip will be   permanently banned.<br>
<br>
3.Pimpandhost have the right to delete, move or replace any uploaded   image which comes under the category of copyrighted material, harassment   or offensive material  and have no responsibility for lost image or   image url.<br>
<br>
4.You are responsible for maintaining the confidentiality of the   password and your account security and are fully responsible for all   activities that occur under your password or account. You agree to   immediately notify     Pimpandhost of any unauthorized use of your password or account or any   other breach of security, and ensure that you     sign out from your account at the end of each session. Pimpandhost will   not be or will not take any responsibility for any loss or damage   arising from your failure to     comply with the rule.<br>
<br>
5.Pimpandhost have the right to ban or suspend account   of any user   who will not be follow rules and Tos of Pimpandhost.<br>
<br>
6.Pimpandhost have  the right to remove any content that compromises with the security of     Pimpandhost servers or Pimpandhost staff.<br>
<br>
 7.All legal adult images are allowed.<br>
<br>
8.Uploading child porn or any     child abuse images will result in immediate ban and all earnings will be     canceled. Further in this kind of case Pimpandhost will work and provide full     support and information to legal authorities. Pimpandhost is strictly against     child abuse and we work with National Center for Missing &amp; Exploited Children     and will cooperate with them in case of any child abuse/porn/harrasment conntent     is found by any user of Pimpandhost.<br>
<br>
9.Uploading any offending adult content/animal abuse or porn/child abuse or     porn or any adult content which is offending will result in permanent ban.<br>
<br>

</div>
 
<p>Thank you.</p> 

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')) { ?>

        <div class="alert alert-success">
            <?= (Yii::$app->session->getFlash('contactFormSubmitted')) ?>
        </div>

    <?php } else { ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 'name') ?>
                    </div>

                    <div class="col-md-6">
                        <?= $form->field($model, 'email') ?>
                    </div>
                </div>


                <?=
                $form->field($model, 'subject')
                    ->dropDownList([
                        'Advertising' => 'Advertising',
                        'General Question' => 'General Question',
                        'Suggestion' => 'Suggestion',
                        'Other' => 'Other'
                    ], [
                        'prompt' => '(Select a subject)'
                    ])
                ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <?=
                $form->field($model, 'verifyCode')
                    ->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-xs-6">{input}</div><div class="col-xs-6">{image}</div></div>',
                    ])
                ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    <?php } ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/faq.php
<?php
/**
 * @var $this \yii\web\View
 */

use yii\helpers\Url;

?>
<div>
    <h1>Signing Up</h1>
    <p>If you would like to submit posts, or leave comments you have to sign up. You can do so by going here.</p>
    <p><a href="<?= Url::to(['site/signup'], true) ?>"><?= Url::to(['site/signup'], true) ?></a></p>
    <p>Make sure you have a working email because you will need to confirm it's actually a working email, and you are a
        real person. if your cat wants to signup, well, he or she will also have to have their own working email. The
        signup
        process is pretty straight forward, add your email, pick a name and a password. If you've used a computer some
        time
        in your life you shouldn't have a problem. If you're new to the internet, well, glad you picked us first but you
        still need all of the above.</p>

    <h1>Posting</h1>
    <p>This is where things may be a little tricky for some of you, others may have no problem. We have several ways you
        can add content, whether it be videos from youtube, or pictures you took of your cousin when he had a little too
        much to drink and you drew schlongs on his face (try not to upload those though, we're trying to keep the site
        SFW
        so you can send stuff yo grandma and not give her a heart-attack in the process).</p>
    <p>Now, onto posting.</p>
    <ol class="list-unstyled numeric-list">
        <li>
            - Add a Title, make it catchy, if its your cat doing something funny, be witty about it. Don't just say
            "Whiskers on Catnip" say "Whiskers traveling to a parallel universe on that catnip" or something even better
            than that lame one I just used as an example.
        </li>
        <li>
            - Add the content, you can embed a YouTube video just by clicking the play button icon, adding the link,
            and hitting add, eezy peezy! You can add images by clicking the center icon and add up to 100 pics. You can
            also add some text by clicking the first icon if you want to give a description of each picture.
        </li>
        <li>
            - You can rearrange the stuff simply by moving your mouse over the 3 bars on the left side and dragging it
            into the spot you would like. You can also delete stuff you didn't mean to add, or click the + icon and add
            something else above it.
        </li>
        <li>
            - Add tags, this helps people find the content you post. Don't go insane and post like 400 tags that have
            nothing to do with the post. It just pisses people off.
        </li>
        <li>
            - "Is Author" if you took the pic, click that. If you jacked it from somewhere else because you thought it
            was funny and needed to be shared, don't click it.
        </li>
        <li>- "Is Adult" look, no porn. But if something is a little risque but no nudity, share that shiznit.</li>
        <li>
            - Save Draft, if you're about to miss your favorite tv show and still want to post it, just hit save
            draft. Come
            back later and finish it and submit it. It'll still be there ready and waiting like that girl you once had
            who never called back because well... she wasn't impressed by your skills in the sack.
        </li>
        <li>
            - "Preview" it is what it says it is, preview the post before setting it live for the world to see. I'd
            suggest using it and going over everything you wrote just so the grummer nazes don't attack you. See what I
            did there?
        </li>
    </ol>
    <p>
        Finally, click Save post. When you click this it'll go to the "New" section, if it does well there it may even
        make it to the homepage. If it does you get points, which leads us to the next subject...
    </p>
    <p>How to take a bath in hot chocolate and why it's great for your skin.</p>
    <p>Wait. Crap. Wrong tutorial.</p>
    <p>Ah, yeah, onto the points system.</p>
    <p>See that up and down with a number between it on the left side of every post? That's an upvote and downvote
        button.
        You click that when you like or dislike something, the more upvotes something you post gets, the more points you
        accumulate. The more you accumulate the more people like you and the less you need to go outside because you
        have
        people that like you right here on the site. Well, not really. They just like you for your content. Needless to
        say,
        #upvotesmatter , its a new movement gaining traction, so I hear. The more points you get, the more badges you
        get.
        Eventually we'll give you prizes as the site grows if you consistently post good stuff. If you post horrible
        stuff
        no one likes, well, stop. Find better content.
    </p>

    <h1>Sharing</h1>
    <p>This is actually extremely important if you're posting content to share it to your social networks, emailing it
        to
        your friends, your mom, your uncle who you rarely talk to but like to keep in touch with because he sends money
        every year for Christmas and your birthday. Ect. On the left side of each post you'll see the google, twitter
        and
        facebook icons, click them, share away. If you want to share to others just copy and paste the URL.
    </p>

    <h1>Favorite Posts</h1>
    <p>See the star under the sharing options? This allows you to favorite the stuff you really like so you can easily
        find
        it again in the future.
    </p>

    <h1>Commenting</h1>
    <p>This is where the fun really happens, when people start commenting, arguing, trolling, ect. Or posting titles
        that
        are actually better than the ones the original poster made. Mostly its just to use words to express your love
        for
        how great the content is, or how much you hated it. Which usually leads to someone else saying the opposite,
        then
        you two bicker as others join in, that's why we included the reply option to each comment, so the comments can
        be
        nested instead of it looking like a bunch of random comments to people that posted something halfway up the
        page.
    </p>
    <p>We also allow you to vote up/vote down comments. If a comment gets enough downvotes it will be hidden so others
        aren't subjected to the stupidity of a few morons who just like to type crap online.</p>
    <p>We also allow you to sort the comments by Best (Highest rated) and Newest.</p>

    <h1>Quick Scroll</h1>
    <p>See those up/down arrows in the bottom right hand of the page? Those help you skip to the next post without
        having
        to scroll, the one pointing Up with the bar above it jumps back to the top of the page.
    </p>

    <h1>Search</h1>
    <p>I feel like I shouldn't have to explain this, but if you're new to the internet and want to find something, this
        is
        how you find it on our site. Also, there is a theory going around if you type in a certain series of letters and
        numbers the screen literally opens a time portal that allows you to search through time. I tried it once, and I
        must
        say, the Dinosaurs weren't really all they're made out to be. Made fun of a T-Rex for his little arms and all he
        did
        was turn his back and walk away crying, like a lil bitch.
    </p>

    <p>Well, that's how you use the site. We'll be updating this as new features are added. So if you don't know how to
        do
        something that's new on the site, just check back here. We'll walk you through it.
    </p>
</div>

views/site/index.php
<?php \app\assets\MainPageAsset::register($this); ?>
<div id="main-page">
    <?= \app\widgets\FullUploader::widget([
        'uploaderOptions' => [
            'disabledBeforeLoad' => true,
            'buttonOptions' => [
                'id' => 'main-button'
            ],
            'fileInputInsideContainer' => false,
            'js' => [
                'clicker' => '#main-button',
                'fileInput' => "#main-page-file-input",
                'fileInputInsideContainer' => false,
            ]
        ]
    ]); ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use app\widgets\AuthChoice;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Alert::widget();?>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<?= Breadcrumbs::widget(
				[
					'encodeLabels'=>false,
					'homeLink'=>[
						'label'=>'<i class="fa fa-home"></i>',
						'url'=>['post/index']
					],
					'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
				]
			) ?>

			<?php $form = ActiveForm::begin([]); ?>
			<div class="panel panel-default">
				<div class="panel-body">
					<h3><i class="fa fa-sign-in"></i> Sign-in</h3>
					<hr>
					<?= $form->field($model, 'loginId')->label(false)->textInput(['placeholder' => 'Email or Username']) ?>
					<?= $form->field($model, 'password')->label(false)->passwordInput(['placeholder' => 'Password']) ?>
					<?= Html::a('Forgot Password?', ['site/reset']) ?>
					<?= $form->field($model, 'rememberMe')->checkbox(['class']) ?>

					<div class="pull-left">Or login with:</div>
					<?php
					$authAuthChoice = AuthChoice::begin(
						[
							'baseAuthUrl' => ['site/auth']
						]
					);

					echo Html::ul(
						array_map(
							function ($client) use ($authAuthChoice) {
								return Html::a('<i class="fa fa-' . $client->getName() . ' fa-2x fa-fw"></i>', $authAuthChoice->createClientUrl($client));
							},
							$authAuthChoice->getClients()
						),
						[
							'encode' => false,
							'class' => 'list-inline pull-right'
						]
					);
					AuthChoice::end();
					?>
					<div class="clearfix"></div>
					<hr>
					<div class="text-center">
						<div class="btn-group" role="group">
							<?= Html::submitButton('<i class="fa fa-check"></i> Login', ['class' => 'btn btn-primary']) ?>
							<?= Html::a('<i class="fa fa-user-plus"></i> Create an account', ['site/signup'], ['class' => 'btn btn-default']) ?>
						</div>
					</div>
				</div>
				<?php $form::end(); ?>
			</div>
		</div>
	</div>
</div>

views/site/reset.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Sign up';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">

			<?php $form = ActiveForm::begin(
				[
//					'action'=>['user/request-password-reset']
				]
			); ?>
			<div class="panel panel-default">
				<div class="panel-body">
					<h3><i class="fa fa-mail-forward"></i> Forgot Password?</h3>

					<p class="hint">
						Enter your e-mail address below to reset your password.
					</p>
					<hr>
					<?= $form->field($model, 'email')
							 ->textInput(['placeholder' => $model->getAttributeLabel('email')])
							 ->label(false);
					?>

					<hr>
					<div class="text-center">
						<div class="btn-group" role="group">
							<?= Html::submitButton(
								'Request',
								[
									'class' => 'btn btn-success uppercase',
								]
							) ?>

							<?= Html::a(
								'Cancel',
								['site/login'],
								[
									'class' => 'btn btn-default',
								]
							) ?>
						</div>
					</div>
				</div>
			</div>

			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>

views/site/search.php
<?php
/**
 * @var \app\models\MainSearchForm $searchForm
 * @var \app\components\SphinxDataProvider $dataProvider
 */

\app\assets\SearchPageAsset::register($this);
$totalFound  = $dataProvider->getTotalCount();
$title = $totalFound > 0
    ? 'Search results for "' . preg_replace("/^(my:)/", "", $searchForm->q) . '"'
    : 'Nothing was found for "' . $searchForm->q . '"';
$this->title = $title;

?>
<div id="search-page">

    <h3><?= $title ?></h3>
    <?php if($totalFound > 0): ?>

        <?= \app\widgets\SelectionBar::widget([
            'show' => $dataProvider->totalCount > 0,
            'showAuthorIcons' => !\Yii::$app->user->isGuest &&  \Yii::$app->user->identity->is_admin
        ]) ?>
        <?= \app\widgets\ShareLinksModal::widget(); ?>
        <?= $this->render("//album/_image_list", compact('dataProvider')); ?>
    <?php endif; ?>
</div>

views/site/test.php
<h1>Current user #<?= Yii::$app->user->isGuest? 'Guest':Yii::$app->user->identity->displayName?></h1>

<?= $this->render('/post/view',compact('postId','type')) ?>