models/Album.php
<?php

namespace app\models;

use app\components\ActiveRecord;
use app\helpers\SortHelper;
use app\models\behaviors\Rating;
use app\models\interfaces\CommentsServiceModel;
use Yii;
use yii\db\Exception;
use yii\helpers\Json;
use yii\helpers\Url;
use app\components\behaviors\AlbumImageCommon;
use app\components\behaviors\HasOwner;

/**
 * This is the model class for table "album".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $password
 * @property string $contentDisplay
 * @property integer $status
 * @property integer $imageCount
 * @property integer $viewsCount
 * @property integer $imageSize
 * @property integer $commentCount
 * @property integer $type
 * @property integer $defaultImageId
 * @property string $commentKey
 * @property string $privateKey
 * @property string $guestKey
 * @property integer $authorId
 * @property string $updateTime
 * @property string $createTime
 *
 * @property User $author
 * @property Image[] $images
 */
class Album extends ActiveRecord implements CommentsServiceModel
{
    const UNSORTED_TITLE = 'Unsorted';

    const SCENARIO_AUTO_CREATING = 'auto_creating';
    const SCENARIO_LOCKING = 'locking';
    const SCENARIO_CREATING_BY_USER = 'creating_by_user';

    const SESSION_PASSWORD_KEY = 'alpa';


    const TYPE_USER        = 0;
    const TYPE_UNSORTED    = 1;
    const TYPE_TRASH       = 2;
    const TYPE_SCREENSHOTS = 3;
    const TYPE_PIMPED      = 4;
    const TYPE_WATERMARKS  = 5;
    const TYPE_GUEST       = 10;
    const TYPE_SAMPLE      = 11;



    const STATUS_NORMAL = 0;
    const STATUS_DELETED = 1;
    //@todo do we need it?
    const STATUS_PRIVATE = 2;

    const TITLE_UNTITLED = 'Untitled';


    private $_isUnsorted = false;

    const MAX_SHARE_CODES = 100;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'album';
    }



    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['ownerBehavior'] = [
            'class' => HasOwner::className()
        ];

        $behaviors['albumImageCommon'] = [
            'class' => AlbumImageCommon::className(),
        ];

        $behaviors['rating'] =[
            'class' => Rating::className()
        ];

        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['title', 'required'],
            ['password', 'default', 'value' => ''],
            ['password', 'required', 'on' => self::SCENARIO_LOCKING],

            [['content', 'contentDisplay','password'], 'string'],
            [['status', 'imageCount', 'imageSize', 'commentCount', 'defaultImageId', 'authorId','totalViews', 'todayViews'], 'integer'],
            [['updateTime', 'createTime'], 'safe'],
            ['type', 'default', 'value' => self::TYPE_USER],
            ['type', 'in', 'range' => [
                 self::TYPE_USER, self::TYPE_UNSORTED, self::TYPE_TRASH, self::TYPE_SCREENSHOTS,
                    self::TYPE_PIMPED,self::TYPE_WATERMARKS, self::TYPE_GUEST, self::TYPE_SAMPLE
            ]],
            [['title', 'commentKey', 'privateKey', 'guestKey'], 'string', 'max' => 255],
            [['authorId'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['authorId' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'contentDisplay' => 'Content Display',
            'status' => 'Status',
            'imageCount' => 'Image Count',
            'imageSize' => 'Image Size',
            'commentCount' => 'Comment Count',
            'defaultImageId' => 'Default Image ID',
            'commentKey' => 'Comment Key',
            'privateKey' => 'Private Key',
            'guestKey' => 'Guest Key',
            'authorId' => 'Author ID',
            'updateTime' => 'Update Time',
            'createTime' => 'Create Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'authorId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages($imageStatus = [Image::STATUS_NORMAL, Image::STATUS_PROCESSING])
    {
        if($this->getIsUnsorted()){
            return Image::find()->where(['status' => $imageStatus, 'authorId' => $this->authorId, 'albumId' => null]);
        }else{
            return $this->hasMany(Image::className(), ['albumId' => 'id'])->where(['status' => $imageStatus]);
        }
    }


    public function beforeSave($insert)
    {
        if($insert && $this->isNewRecord && empty($this->createTime)){
            $this->createTime = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function belongsToUser($user)
    {
        if($user instanceof User){
            return $this->authorId == $user->id;
        }

        return $this->authorId == $user;
    }

    public static function createUnsorted($userId)
    {
        $album = new self;
        $album->authorId = $userId;
        $album->makeUnsorted();
        $album->title = self::UNSORTED_TITLE;
        return $album;
    }


    public static function create($attributes, $scenario = null)
    {
        $album = new self;

        if($scenario){
            $album->setScenario($scenario);
        }
        $album->setAttributes($attributes);
        $album->save();
        return $album;
    }

    public function getCommentsUrl()
    {
        return Url::to(['/album/item', 'id' => $this->id, '#' => 'comments-block']);
    }

    public function getUrl($scheme = false)
    {
        $route = $this->getIsUnsorted() ? ['album/unsorted'] : ['/album/item', 'id' => $this->id];
        return Url::to($route, $scheme);
    }

    public function getIsLocked()
    {
        if(empty($this->password) && !empty($this->privateKey))
        {
            $this->setPassword($this->privateKey);
            $this->privateKey = null;
            if(!$this->save()){
                throw new Exception("Can't convert password : " . json_encode($this->getErrors()));
            }
        }
        return !empty($this->password);
    }

    public function unlock()
    {
        $tr = $this->getDb()->beginTransaction();
        if($this->setImagesStatus(Image::STATUS_NORMAL) !== false)
        {
            $this->password = '';
            $this->status = self::STATUS_NORMAL;
            if($this->save())
            {
                $tr->commit();
                return true;
            }
        }
        $tr->rollBack();
        return false;
    }

    public function lock($password)
    {
        $tr = $this->getDb()->beginTransaction();
        if($this->setImagesStatus(Image::STATUS_PRIVATE) !== false)
        {
            $this->setScenario(Album::SCENARIO_LOCKING);
            $this->setPassword($password);
            $this->status = self::STATUS_PRIVATE;
            if($this->save())
            {
                $tr->commit();
                return true;
            }
        }

        $tr->rollBack();
        return false;
    }


    public function setImagesStatus($status, $updatedStatuses = [Image::STATUS_NORMAL, Image::STATUS_PROCESSING, Image::STATUS_PRIVATE])
    {
        if(!in_array($status, [
            Image::STATUS_PRIVATE,
            Image::STATUS_NORMAL,
            Image::STATUS_DELETED,
            Image::STATUS_PROCESSING,
            Image::STATUS_DELETED_FOREVER,
        ])){
            $this->addError("id","Wrong status to be set for album images");
            return false;
        }

        return $this->getDb()
            ->createCommand()
            ->update(Image::tableName(), ['status' => $status], ['albumId' => $this->id, 'status' => $updatedStatuses])
            ->execute();
    }

    public function setPassword($password)
    {
        $this->password = \Yii::$app->security->generatePasswordHash($password);
    }


    public function validatePasswordHash($passwordHash)
    {
        return $this->password === $passwordHash;
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        if($this->getIsUnsorted()){
            throw new Exception("This album is Unsorted, it's impossible to save");
        }
        return parent::save($runValidation, $attributeNames);
    }

    public function softDelete()
    {
        $tr = $this->getDb()->beginTransaction();
        $removeImages = true;
        if(!$this->getIsUnsorted())
        {
            $this->status = self::STATUS_DELETED;
            $removeImages = $this->save();
        }
        if($removeImages){
            list($removed, $unremoved) = $this->softDeleteImages();
            if(count($unremoved) == 0){
                $tr->commit();
                return true;
            }else{
                $this->addError("albumId", "Cound't soft delete images:" . Json::encode($unremoved));
            }
        }

        return false;
    }

    public function softDeleteImages()
    {
        $images = $this->getImages([Image::STATUS_NORMAL, Image::STATUS_PROCESSING, Image::STATUS_PRIVATE])->all();
        $removed = [];
        $unremoved = [];
        foreach($images as $image){
            if($image->softDelete()){
                $removed[] = $image->id;
            }else{
                $unremoved[$image->id] = $image->getErrors();
            }
        }

        return [$removed, $unremoved];
    }


    public function addArchiveToQueue($userId)
    {
        $archive = new Archive();
        $archive->authorId = $userId;
        $archive->setScenario(Archive::SCENARIO_ADDING_TO_QUEUE);
        $archive->setTitleForAlbum($this->title);

views/album/_album.php
<?php

use app\helpers\Html;
use yii\helpers\Url;
use app\models\Image;

/**
 * @var $this yii\web\View
 * @var $model \app\models\Album;
 *
 */
$images = $model->getImages([Image::STATUS_NORMAL, Image::STATUS_PROCESSING, Image::STATUS_PRIVATE])->limit(4)->all();
$imagesCount = $model->getImageCount();

?>
<div class="ar">
    <a href="<?= Url::to(['album/item', 'id'=>$model->id], true) ?>"
       class="grid-content album-thumb"
   >
        <?php foreach($images as $i => $image){
            echo Html::inlineImageStyle($image->id, $image->getHttpFtpFileName(\app\models\Image::SIZE_0_PX));
        }?>

        <i class='fa fa-lock thumb-lock-icon' <?= !$model->getIsLocked() ? "style='display:none'" : "" ?>></i>

        <ul class="album-cover">
            <?php foreach($images as $i => $image):
                ?>
                <li class="center-cropped image_<?= $image->id ?>">
                </li>
            <?php
                if($i == 3){
                    break;
                }
                endforeach;
            ?>
        </ul>
    </a>
</div>
<div class="content-title">
    <div class="album-title">
    <?= Html::a($model->title, ['album/item', 'id' => $model->id], ['title' => $model->title]) ?>
    </div>
    <div class="album-info">
        <?= $imagesCount ?> image<?= $imagesCount !== 1 ? "s" : "" ?>
        <?= date("F j, Y  ", strtotime($model->createTime)) ?>
          <?php
                $stats = $model->getViewsStatistic();
                echo \app\widgets\PopoverViewsStats::widget([
                    'stats' => $stats,
                    'content'=> $stats['unique']['total']
                ])
            ?>  view<?= $stats['unique']['total'] !== 1 ? "s" : "" ?>
    </div>
</div>

<div class="hover-donor" style="display: none">
    <?php
    $lockStatus = $model->getIsLocked() ? ["lock", "Unlock"] : ["unlock", "Lock"];
    if($model->checkAuthorAccess()){

        $hoverContent = '<i class="fa fa-download" title="Download album"></i>'.
        '<i class="fa fa-trash-o" title="Remove album"></i>' .
        '<i class="fa fa-share-alt" title="Get share codes for this album"></i>' .
        '<i class="fa fa-picture-o" title="Go to album page"></i>'.
        "<i class='unlock-icon fa fa-" . $lockStatus[0] . "' title='" . $lockStatus[1] .
        " this album' data-locked='" . (int) $model->getIsLocked() . "'" .
            " data-id='".$model->id."'></i>";
    }else{
        $downloadIcon = !\Yii::$app->user->isGuest ? '<i class="fa fa-download" title="Download album"></i>': "";
        $hoverContent = $downloadIcon .
        '<i title="Share image" class="fa fa-share-alt"></i>'.
        '<i title="See full image" class="fa fa-picture-o"></i>';

    }

    ?>
    <div class="hover-bar-content"><?= $hoverContent ?></div>
</div>

views/album/_album_image.php
<?php

use app\helpers\Html;
use app\helpers\HtmlPurifier;
use yii\helpers\Url;

/**
 * @var $this yii\web\View
 * @var $model \app\models\Image;
 *
 */

?>
<?= Html::inlineImageStyle($model->id, $model->getHttpFtpFileName(\app\models\Image::SIZE_SMALL_PX)) ?>

<div class="ar">
    <div class="grid-content">
    <?php
        echo Html::a("",
            Url::to(['image/show', 'id' => $model->id], true),
            [
                'class' => 'image-wrapper center-cropped im-wr image_' . $model->id,
                'data-src' => $model->getHttpFtpFileName(false, false),
                'data-filename' => $model->fileName,
                'data-size' => $model->size,
                'target' => '_blank'
        ]);
    ?>
    </div>
</div>


<?php

$disabledClass = $model->getIsProcessing() ? " icon-disabled" : "";
$disabledTitle = $model->getIsProcessing() ? " (disabled while processing)" : "";

if(empty($hoverContent)){
    $hoverContent = $model->checkAuthorAccess(false)
        ?
        '<i title="Download image' . $disabledTitle. '" class="fa fa-download' . $disabledClass . '"></i>'.
        '<i title="Remove image" class="fa fa-trash-o"></i>' .
        '<i title="Edit image' . $disabledTitle . '" data-url="'. Url::to(['image/edit', 'id'=>$model->id]).'" class="fa fa-edit' . $disabledClass . '"></i>' .
        '<i title="Share image" class="fa fa-share-alt"></i>'.
        '<i title="See full image" class="fa fa-picture-o"></i>'
        :
        '<i title="Download image" class="fa fa-download"></i>'.
        '<i title="Share image" class="fa fa-share-alt"></i>'.
        '<i title="See full image" class="fa fa-picture-o"></i>';
}
?>

<div class="hover-donor" style="display: none">
    <div class="hover-bar-content"><?= $hoverContent ?></div>

    <div class="hover-info-content">
        <div class="content-header" title="<?= $model->getOriginalName() ?>"><?= $model->getOriginalName() ?></div>
        <div class="content-info">Size <?= $model->getSizeInKb() ?> kB <?php
            $stats = $model->getViewsStatistic();
            echo \app\widgets\PopoverViewsStats::widget([
                'stats' => $stats,
                'options' => [
                    'data-placement' => 'top'
                ],
                'content'=> $stats['unique']['total']
            ])
            ?>  view<?= $stats['unique']['total'] !== 1 ? "s" : "" ?></div>
    </div>

</div>

views/album/_bread_crumbs.php
<?php
use yii\helpers\Url;

$urlParams = \Yii::$app->user->isGuest || $album->authorId != \Yii::$app->user->id ?
    ['album/user', 'id'=>$album->authorId] : ['album/my'];

$breadcrumbsLinks = [];

if($album->uploadedByGuest()){
    if(!$album->getIsUnsorted()){
        $breadcrumbsLinks = array_merge($breadcrumbsLinks,[['label' => $album->title]]);
    }
}else
{
    $urlParams = \Yii::$app->user->isGuest || $album->authorId != \Yii::$app->user->id ?
        ['album/user', 'id'=>$album->authorId] : ['album/my'];

    $breadcrumbsLinks = array_merge($breadcrumbsLinks, [
        ['label' => $album->author->username, 'url' => $urlParams],
        ['label' => $album->title]
    ]);
}



?>
<?= \app\components\widgets\Breadcrumbs::widget([
    'links' => $breadcrumbsLinks
]) ?>

views/album/_donor_image_content.php
<?php

$disabledClass = $model->getIsProcessing() ? " icon-disabled" : "";
$disabledTitle = $model->getIsProcessing() ? " (disabled while processing)" : "";

if(empty($hoverContent)){
    $hoverContent = $model->checkAuthorAccess()
        ?
        '<i title="Download image' . $disabledTitle. '" class="fa fa-download' . $disabledClass . '"></i>'.
        '<i title="Remove image" class="fa fa-trash-o"></i>' .
        '<i title="Edit image' . $disabledTitle . '" data-url="'. Url::to(['image/edit', 'id'=>$model->id]).'" class="fa fa-edit' . $disabledClass . '"></i>' .
        '<i title="Share image" class="fa fa-share-alt"></i>'.
        '<i title="See full image" class="fa fa-picture-o"></i>'
        :
        '<i title="Download image" class="fa fa-download"></i>'.
        '<i title="Share image" class="fa fa-share-alt"></i>'.
        '<i title="See full image" class="fa fa-picture-o"></i>';
}
?>

<div class="hover-donor" style="display: none">
    <div class="hover-bar-content"><?= $hoverContent ?></div>

    <div class="hover">
        <div class="content-header" title="<?= $model->getOriginalName() ?>"><?= $model->getOriginalName() ?></div>
        <div class="content-info">Size <?= $model->getSizeInKb() ?> kB <?php
            $stats = $model->getViewsStatistic();
            echo \app\widgets\PopoverViewsStats::widget([
                'stats' => $stats,
                'options' => [
                    'data-placement' => 'top'
                ],
                'content'=> $stats['raw']['all']
            ])
            ?>  view<?= $stats['raw']['all'] !== 1 ? "s" : "" ?></div>
    </div>

</div>

views/album/_image_list.php
<?php $isLargeLayout = !isset($isLargeLayout) ? true : $isLargeLayout;
$displaySorter = isset($displaySorter) ? $displaySorter : false;
$sorterLayout = $displaySorter ? "{sorter}<div class='clearfix'></div>" : "";
?>


<div>
    <?php
    \yii\widgets\Pjax::begin(['id'=>'pjax-listview', 'linkSelector' => false]);

    $class = 'image-block col-md-4 col-xs-4 col-xxs-6';
    if($isLargeLayout){
        $class .= ' col-lg-3';
    }
    $config = [
        'id' => 'image-list-container',
        "layout" => "$sorterLayout<div id='album-images'>{items}</div>\n <div class='clearfix'></div>{pager}{summary}",

        'itemOptions'=> ['class' => $class],
        'dataProvider' => $dataProvider,
        'itemView' => '_album_image',
        'emptyText' => false,
        'emptyTextOptions' => ['id' => 'album-images'],
        'options' => [
            'data-removeUrl'=> \yii\helpers\Url::to(['image/delete'])
        ],
        'pager' => [
            'class' => \app\widgets\LinkPager::className(),
            'countOnPage' => $dataProvider->getCount(),
        ],
        'summary' => false
    ];

    if($displaySorter)
    {
        $config['sorter'] = [
            'class' => \app\widgets\DropdownSorter::className(),
            'userSortSetting' => \app\models\UserSettings::NAME_IMAGES_SORTING,
            'attributes' => [
                'title',
                'Size' => 'size',
                'Uploaded' => 'createTime',
                'Modified' => 'updateTime'
            ]
        ];
    }



    if(!empty($hoverContent)){
        $config['viewParams'] = ['hoverContent' => $hoverContent];
    }

    echo \app\components\widgets\ListView::widget($config);

    \yii\widgets\Pjax::end();
    ?>

</div>

views/album/_lock_form_modal.php
<?php
use yii\bootstrap\ActiveForm;

?>

<?php \yii\bootstrap\Modal::begin([
    'id'=>'lock-album-modal',
    'header' => '<h4>Set password</h4>',
    'toggleButton' => false,
    'footer' => "<button type='button' class='btn btn-primary' id='btn-set-password'>Save</button>"
]); ?>

<?php $form = ActiveForm::begin([
    'id' => 'album-lock-form',
    'action' => ['album/lock']
]);

?>
<?= $form->field($lockForm, 'password')->passwordInput() ?>
<?php ActiveForm::end(); ?>

<?php \yii\bootstrap\Modal::end(); ?>

views/album/_set_password_modal.php
<?php
use yii\bootstrap\ActiveForm;
?>

<?php \yii\bootstrap\Modal::begin([
    'id'=>'create-album-modal',
    'header' => '<h4>Set password</h4>',
    'toggleButton' => false,
    'footer' => "<button type='button' class='btn btn-primary' id='btn-set-password'>Save</button>"
]); ?>

<?php $form = ActiveForm::begin([
    'id' => 'album-lock-form',
    'action' => ['album/ajax-create']
]);

$passwordForm = new \app\models\forms\SetPassword();
?>
<?= $form->field($passwordForm, 'password')->passwordInput() ?>
<?php ActiveForm::end(); ?>

<?php \yii\bootstrap\Modal::end(); ?>

views/album/item.php
<?php
/**
 * @var $album app\models\Album
 * @var $imagesDataProvider \yii\data\ActiveDataProvider;
 * @var $this \yii\web\View
 *
 */

use app\components\View;
use app\helpers\WidgetHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\YTExternalAsset;
use app\models\Image;

\app\assets\AlbumAsset::register($this);
YTExternalAsset::register($this);
$isMine = !\Yii::$app->user->isGuest && $album->authorId == \Yii::$app->user->id;
$lockStatus = false;
if(!$album->getIsUnsorted())
{
    $this->title = Html::encode($album->title) . ' | ' . \Yii::$app->name;
    $lockStatus = $album->getIsLocked() ? ["lock", "Unlock"] : ["unlock", "Lock"];

    $config = WidgetHelper::getConfig(2);
    $ck = WidgetHelper::getScriptInView('//js/widget', ['config' => $config]);
    $this->registerJs($ck, View::POS_END);
}

$totalCount = $album->getImageCount();
$models = $imagesDataProvider->getModels();

if(isset($models[0]))
{
    $this->registerMetaTag(['property' => 'og:image', 'content' => $models[0]->getHttpFtpFileName(Image::SIZE_0_PX)]);
    $this->registerMetaTag(['property' => 'og:image:width', 'content' => Image::SIZE_0_PX]);
    $this->registerMetaTag(['property' => 'og:image:height', 'content' => Image::SIZE_0_PX]);
}

$this->registerMetaTag([
    'name' => 'description',
    'content' => 'Pimp and host'
], 'description');

$this->registerMetaTag([
    'name' => 'keywords',
//    'content' => $album->getTagList(',') ?: 'owned,jokes,fun,humour,funny videos,epic,fail,win,funny pics,like a boss,forever alone,meme,gifs,funny gifs,trolling'
], 'keywords');

if(!$album->getIsUnsorted() && $album->checkAuthorAccess())
{
    echo \app\widgets\AlbumLocker::widget();
}

echo \app\widgets\ShareLinksModal::widget();
echo \app\widgets\BlueimpGallery::widget();
echo \app\widgets\AlbumPicker::widget([
    'albumIds' => $albumsForMoving
]);
?>
<div id="album-page" class="post item-post album"
     data-widget="page"
     data-page-key="album_<?= $album->id ?>"
     data-key="<?= $album->id ?>"
     data-remove-url="<?= Url::to(['album/remove']); ?>"
     data-remove-redirect-url="<?= Url::to(['album/my']); ?>"
     data-download-url="<?= Url::to(['album/download']) ?>"
     data-archive-list-url="<?= Url::to(['/archive/list']) ?>"
>

    <div class="clearfix"></div>
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="post-header-main">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="author-header">

                            <?php if($isMine): ?>
                                <div class="pull-right">
                                   <?= \app\widgets\UploaderPopup::widget([

                                           'modalId' => 'album-popup-uploader',
                                           'buttonOptions' => [
                                               'id' => 'add-image-btn',
                                               'class' => 'btn btn-pah add-image-btn',
                                               'label'=> '<i class="fa fa-plus-circle fa-2x"> </i> <span>Add image</span>',
                                               'title'=> "Add image to this album"
                                           ],

                                           'clicker' => false,
                                           'modalTitle' => "Upload images to '" . $album->title . "'",

                                           'fullUploaderOptions' => [
                                           'albumId' => $album->id,
                                           'uploaderOptions' => [
                                               'registerAsset' => false,
                                               'buttonOptions' => [
                                                   'id' => 'album-fb'
                                               ],
                                               'js' => [
                                                   'previewsContainer' => '#album-images',
                                                   'clicker' => '#album-fb',
                                               ],
                                           ],

                                           'loadAlbumPage' => false,
                                       ]
                                   ]);?>

                                </div>
                            <?php elseif(!$album->getIsUnsorted()): ?>
                                <div class="widget-rating widget-rating-scores">
                                    <div data-rating="page"
                                         data-rating-type="scores"
                                         data-rating-key="album_<?= $album->id ?>"
                                         data-rating-value="<?= $album->rating ?>">
                                    </div>
                                </div>
                            <?php endif; ?>

                            <?= \app\widgets\BreadcrumbsHeader::widget([
                                'author' => $isMine ? \Yii::$app->user->identity : $album->author,
                                'links' => [
                                    [
                                        'label' => \app\widgets\Editable::widget(['model' => $album]),
                                    ]
                                ],
                                'afterLinksContent' => $this->render('_title_icons', [
                                    'isMine' => $isMine,
                                    'album' => $album,
                                    'lockStatus' => $lockStatus
                                ])
                            ]) ?>
                        </div>

                        <?= $this->render("//common/_header_post_info", [
                            'model' => $album,
                            'totalCount' => $totalCount
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="album-ctrl pull-right" <?= $totalCount == 0 ? "style='display:none'": "" ?>>
         <span id="slide-show"
               href="#"
               class="pah-color"
               title="Run slideshow for this album">
                    <i class="fa fa-th"></i> <span>Slideshow</span>
        </span>
    </div>

    <?= \app\widgets\SelectionBar::widget([
        'show' =>$imagesDataProvider->totalCount > 0,
        'showAuthorIcons' => $album->checkAuthorAccess(),
    ]); ?>


    <div class="row collapsing-content">
        <div class="col-xs-12 col-sm-12">
            <div class="collapse in"
                 id="collapsePost-<?= $album->id ?>"
                 aria-expanded="true">

                <?= $this->render('_image_list', ['dataProvider' => $imagesDataProvider, 'displaySorter' => true]) ?>

            </div>
            <div class="clearfix"></div>
            <div class="post-bottom">
                <div class="pull-right manage-right-icons">
                    <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->is_admin): ?>
                        <a href="<?= Url::to(["admin/post-to-socials"]); ?>"
                           class="share-to-socials"
                           title="share to socials">
                            <i class="fa fa-2x fa-share"></i>
                        </a>
                    <?php endif; ?>
                </div>
                <?php if(!$isMine  && !$album->getIsUnsorted()): ?>
                    <span class="widget-rating">
                        <span data-rating="page"
                              data-rating-type="buttons"
                              data-rating-key="page_<?= $album->id ?>"
                              data-rating-value="<?= $album->rating ?>">
                        </span>
                    </span>
                <?php endif; ?>
                <?php if(!$album->getIsUnsorted()): ?>
                    <div class="post-btn-group pull-left">
                        <div class="comm">
                            <a class="post-comments" href="<?= $album->commentsUrl ?>" title="comments">
                                <i class="fa fa-comment"></i>
                                <span data-page="comments-count"></span>
                            </a>
                        </div>
                        <div class="mys">
                            <div id="rrssb-<?= $album->id ?>-bottom">
                                <span class="btn"
                                      title="share"
                                      data-rrssb="button"
                                      data-rrssb-container="#rrssb-<?= $album->id ?>-bottom"
                                      data-rrssb-url="<?= $album->getUrl(true) ?>"
                                      data-rrssb-title="<?= $album->title ?>"
                                </span>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div id="comments-block"></div>
    <div data-comment="comment-widget" id="comments"></div>
</div>

views/album/removed.php
<h2>Album is removed.</h2>